### ISSUE TITLE
Ajuste do endpoint para /clients

### ISSUE THREAD

**Issue by oliveiralex** [RangelMoreira/dscatalog-bootcamp-devsuperior#1]
Boa noite Rangel, tudo bem?

Parabéns pelo trabalho, todos os recursos estão funcionando corretamente, incluindo o tratamento de exceção. Desta forma, seu trabalho foi aceito, no entanto gostaria de alertar sobre dois pontos que demandam ajustes:

O primeiro ponto (mais importante) é que o endpoint proposto no projeto é /clients. No caso, você utilizou /custmer. Seguem alguns exemplos abaixo conforme a especificação do trabalho.

Busca paginada de clientes
GET /clients?page=0&linesPerPage=6&direction=ASC&orderBy=name

Busca de cliente por id
GET /clients/1

O segundo ponto é que como o modelo conceitual do projeto implementado no capítulo (DSCatalog) não inclui a classe Client, neste caso implicitamente era esperado que fosse criado um novo projeto contendo somente a classe Client.

Por favor, faça os ajustes e se tiver qualquer dúvida estou à disposição.

**Comment by RangelMoreira** [comment]
Olá Alexandre, obrigado pelo retorno!

Conforme suas orientações, efetuei os ajustes sugeridos.

Alterei o endpoint para /clients e separei a classe Client em um novo projeto o qual o segue no link abaixo.

https://github.com/RangelMoreira/ClientCRUD

Grato!

**Comment by oliveiralex** [comment]
Obrigado por fazer os ajustes Rangel!

Um abraço!
